baseURL = 'https://mosouka.github.io/IVAR/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'reterminal'
publishDir = “docs”

[params]
  contentTypeName = "posts"
  themeColor = 'paper'

[caches]
  [caches.images]
    dir = ':cacheDir/images'


[languages]
  [languages.en.params]
    title = "IVAR"
    subtitle = "I don't know what to call my project yet"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "IVAR"
      logoHomeLink = "/"
