baseURL = 'https://mosouka.github.io/IVAR/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'reterminal'
[params]
  themeColor = 'paper'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
publishDir = “docs”

